# Generated by Django 3.2.14 on 2022-10-10 20:32

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRegister',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('StaffRegisterId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=300, null=True)),
                ('StaffCode', models.CharField(blank=True, max_length=300, null=True)),
                ('EmailId', models.CharField(blank=True, max_length=300, null=True)),
                ('Phone', models.CharField(blank=True, max_length=30, null=True)),
                ('Permission', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
