# Generated by Django 3.2.14 on 2022-10-10 20:32

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('LogId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('Content', models.TextField(blank=True, null=True)),
                ('UserType', models.CharField(blank=True, max_length=50, null=True)),
                ('UserName', models.CharField(blank=True, max_length=300, null=True)),
                ('UserId', models.CharField(blank=True, max_length=50, null=True)),
                ('LogType', models.CharField(blank=True, max_length=300, null=True)),
                ('JsonData', models.TextField(blank=True, null=True)),
                ('CretedDate', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
