# Generated by Django 3.2.14 on 2022-10-26 23:16

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0002_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPDFData',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('PDFDataId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('UserId', models.CharField(blank=True, max_length=50, null=True)),
                ('CampaignId', models.CharField(blank=True, max_length=50, null=True)),
                ('PDFData', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
