# Generated by Django 3.2.14 on 2022-12-16 06:42

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0003_campaignpdfdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('CommentId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('FromId', models.CharField(blank=True, max_length=50, null=True)),
                ('FromUserTypeId', models.CharField(blank=True, max_length=50, null=True)),
                ('CommentType', models.CharField(blank=True, max_length=50, null=True)),
                ('TypeId', models.CharField(blank=True, max_length=50, null=True)),
                ('CommentDate', models.CharField(blank=True, max_length=300, null=True)),
                ('Comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
