# Generated by Django 3.2.14 on 2022-12-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='DefaultAdvertiserCredits',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='DraftExpiryDays',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='PaymentPendingExpiryDays',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
