# Generated by Django 3.2.14 on 2022-12-28 21:21

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0005_auto_20221221_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('CreditId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('CreditCount', models.CharField(blank=True, max_length=50, null=True)),
                ('Amount', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
