# Generated by Django 3.2.14 on 2022-12-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0006_credits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credits',
        ),
    ]
