# Generated by Django 3.2.14 on 2022-12-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0007_delete_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='CreditsExpiryDays',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
