# Generated by Django 3.2.14 on 2023-01-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0008_sitesettings_creditsexpirydays'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ExcelCredits',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
