# Generated by Django 3.2.14 on 2023-02-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0009_sitesettings_excelcredits'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='UploadingAudioSize',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='UploadingImageSize',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='UploadingMediaKitSize',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
