# Generated by Django 3.2.14 on 2023-02-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0010_auto_20230202_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='FreeCreditOnRequest',
            field=models.IntegerField(default=0),
        ),
    ]
