# Generated by Django 3.2.14 on 2023-02-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0011_sitesettings_freecreditonrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='DefaultListingCountry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='DefaultListingVertical',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
