# Generated by Django 3.2.14 on 2023-03-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0012_auto_20230218_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='AdOpportunityPrompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='MediaLocationPrompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
