# Generated by Django 3.2.14 on 2022-10-08 18:18

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherContact',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('PublisherContactId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('PublisherId', models.CharField(max_length=50)),
                ('Name', models.CharField(blank=True, max_length=300, null=True)),
                ('Designation', models.CharField(blank=True, max_length=300, null=True)),
                ('BioData', models.TextField()),
                ('Expertise', models.TextField()),
                ('Language', models.TextField()),
                ('Email', models.CharField(blank=True, max_length=300, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=300, null=True)),
                ('CountriesHandled', models.TextField()),
                ('LocationHandled', models.TextField()),
                ('TimeZone', models.CharField(blank=True, max_length=50, null=True)),
                ('ProfileImage', models.FileField(blank=True, null=True, upload_to='publisher/profile')),
            ],
        ),
        migrations.CreateModel(
            name='PublisherRegister',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('PublisherId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('MediaName', models.CharField(blank=True, max_length=300, null=True)),
                ('CompanyName', models.CharField(blank=True, max_length=300, null=True)),
                ('BusinessEmail', models.CharField(blank=True, max_length=200, null=True)),
                ('OfficeLocation', models.CharField(blank=True, max_length=300, null=True)),
                ('Country', models.CharField(blank=True, max_length=300, null=True)),
                ('Website', models.CharField(blank=True, max_length=300, null=True)),
                ('ContactName', models.CharField(blank=True, max_length=300, null=True)),
                ('Position', models.CharField(blank=True, max_length=300, null=True)),
                ('BusinessName', models.CharField(blank=True, max_length=300, null=True)),
                ('MobileCode', models.CharField(blank=True, max_length=10, null=True)),
                ('MobileNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('Status', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
