# Generated by Django 3.2.14 on 2022-10-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_publisher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherregister',
            name='DefaultCurrency',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
