# Generated by Django 3.2.14 on 2022-10-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_publisher', '0002_publisherregister_defaultcurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherregister',
            name='TimeZone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
