# Generated by Django 3.2.14 on 2022-10-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_publisher', '0003_publisherregister_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherregister',
            name='ContactsOnOff',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
