# Generated by Django 3.2.14 on 2022-10-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_publisher', '0004_publisherregister_contactsonoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherregister',
            name='RegBy',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
