# Generated by Django 3.2.14 on 2022-11-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_publisher', '0006_meetingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherregister',
            name='ProfileImage',
            field=models.FileField(blank=True, null=True, upload_to='publisher/profile'),
        ),
    ]
