# Generated by Django 3.2.14 on 2022-11-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_publisher', '0008_publishercontact_phonecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherregister',
            name='UserName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
