# Generated by Django 3.2.14 on 2022-12-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_publisher', '0010_auto_20221210_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='MediaId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
