# Generated by Django 3.2.14 on 2022-12-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_publisher', '0011_meetingrequest_mediaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='Status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
