# Generated by Django 3.2.14 on 2023-02-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_publisher', '0012_meetingrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishercontact',
            name='BioData',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publishercontact',
            name='CountriesHandled',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publishercontact',
            name='Expertise',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publishercontact',
            name='Language',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publishercontact',
            name='LocationHandled',
            field=models.TextField(blank=True, null=True),
        ),
    ]
