# Generated by Django 3.2.14 on 2023-03-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_publisher', '0013_auto_20230207_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherregister',
            name='PlanExpiryDate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publisherregister',
            name='PlanStatus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
