# Generated by Django 3.2.14 on 2023-03-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_publisher', '0014_auto_20230318_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherregister',
            name='BotAavatar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='publisherregister',
            name='BotName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publisherregister',
            name='EnableBot',
            field=models.BooleanField(default=False),
        ),
    ]
