# Generated by Django 3.2.14 on 2023-03-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_publisher', '0015_auto_20230319_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisherregister',
            name='PlanStatus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
