# Generated by Django 3.2.14 on 2023-03-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_publisher', '0016_alter_publisherregister_planstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisherregister',
            name='BannerImageForMobile',
            field=models.FileField(blank=True, null=True, upload_to='publisher/banner_image'),
        ),
    ]
