# Generated by Django 3.2.14 on 2023-04-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_publisher', '0018_publisherregister_enablemediaentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisherregister',
            name='EnableBot',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
