# Generated by Django 3.2.14 on 2023-01-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryevent',
            name='CountryNumericCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
