# Generated by Django 3.2.14 on 2023-02-02 05:28

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_brandcategory_campaignobjective'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequiredFor',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('HelpRequiredForId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('HelpRequiredFor', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRequest',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('MeetingRequestId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('PublisherId', models.CharField(max_length=50)),
                ('HelpRequiredFor', models.TextField()),
                ('Message', models.TextField()),
                ('CreatedDate', models.CharField(max_length=200)),
                ('Status', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
