# Generated by Django 3.2.14 on 2023-02-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0005_auto_20230216_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryevent',
            name='CountryTag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
