# Generated by Django 3.2.14 on 2023-02-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0006_countryevent_countrytag'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatedreach',
            name='ReachFrom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estimatedreach',
            name='ReachTo',
            field=models.IntegerField(default=0),
        ),
    ]
