# Generated by Django 3.2.14 on 2023-03-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0007_auto_20230224_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryevent',
            name='CountryOnOFF',
            field=models.IntegerField(default=1),
        ),
    ]
