# Generated by Django 3.2.14 on 2023-03-18 01:48

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0008_countryevent_countryonoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('LocationId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('CityId', models.CharField(max_length=50)),
                ('LocationName', models.CharField(max_length=300)),
            ],
        ),
    ]
