# Generated by Django 3.2.14 on 2023-03-31 06:43

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0010_adunitspecificcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlyRecommendedMedia',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('HighlyRecommendedMediaId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('AudienceId', models.CharField(blank=True, max_length=50, null=True)),
                ('TypeId', models.CharField(blank=True, max_length=50, null=True)),
                ('Type', models.CharField(blank=True, max_length=300, null=True)),
                ('AdUnit', models.TextField(blank=True, null=True)),
                ('Media', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
