# Generated by Django 3.2.14 on 2023-04-03 02:54

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0011_highlyrecommendedmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationBanner',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('RecommendationBannerId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('AudienceId', models.CharField(blank=True, max_length=50, null=True)),
                ('Heading', models.CharField(blank=True, max_length=300, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Caption', models.CharField(blank=True, max_length=300, null=True)),
                ('BannerImage', models.FileField(blank=True, null=True, upload_to='listing_banner')),
                ('AdUnit', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
