# Generated by Django 3.2.14 on 2023-04-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0012_recommendationbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlyrecommendedmedia',
            name='CountryId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recommendationbanner',
            name='CountryId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
