# Generated by Django 3.2.14 on 2023-04-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0013_auto_20230408_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingcategory',
            name='Enable',
            field=models.BooleanField(default=False),
        ),
    ]
