# Generated by Django 3.2.14 on 2022-10-08 18:18

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('CartId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('AdvertiserId', models.CharField(max_length=50, null=True)),
                ('MediaAdTypeId', models.CharField(max_length=50, null=True)),
                ('StartDate', models.CharField(max_length=200, null=True)),
                ('CartStatus', models.IntegerField()),
                ('MediaDetail', models.TextField()),
                ('MediaAdTypeDetail', models.TextField()),
                ('Vertical', models.CharField(max_length=50, null=True)),
                ('Amount', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('PlanId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('AdvertiserId', models.CharField(max_length=50, null=True)),
                ('PlanName', models.CharField(max_length=400, null=True)),
                ('StartDate', models.CharField(max_length=50, null=True)),
                ('EstimateAmount', models.CharField(max_length=20, null=True)),
                ('Currency', models.CharField(max_length=10, null=True)),
                ('Status', models.IntegerField(default=0)),
                ('Approval', models.IntegerField(default=0)),
                ('Payment', models.IntegerField(default=0)),
                ('Creative', models.IntegerField(default=0)),
                ('PlanCreatedDate', models.CharField(max_length=50, null=True)),
                ('PlanExpiryDate', models.CharField(max_length=50, null=True)),
                ('CreativeDocFile', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDetail',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('PlanDetailId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('PlanId', models.CharField(max_length=50, null=True)),
                ('AdvertiserId', models.CharField(max_length=50, null=True)),
                ('MediaAdTypeId', models.CharField(max_length=50, null=True)),
                ('StartDate', models.CharField(max_length=200, null=True)),
                ('MediaDetail', models.TextField()),
                ('MediaAdTypeDetail', models.TextField()),
                ('Vertical', models.CharField(max_length=50, null=True)),
                ('Amount', models.CharField(max_length=20)),
                ('Status', models.IntegerField()),
            ],
        ),
    ]
