# Generated by Django 3.2.14 on 2022-11-16 02:19

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateShorten',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('EstimateShortenId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('PlanId', models.CharField(max_length=50, null=True)),
                ('AdvertiserId', models.CharField(max_length=50, null=True)),
                ('PlanName', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
