# Generated by Django 3.2.14 on 2022-12-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_media', '0002_estimateshorten'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='AdvertiserAssistanceSupport',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='AssistanceSupportCreditUsed',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
