# Generated by Django 3.2.14 on 2022-12-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_media', '0003_auto_20221218_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandetail',
            name='ExpiryDate',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
