# Generated by Django 3.2.14 on 2022-12-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_media', '0004_plandetail_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandetail',
            name='AdvertiserId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plandetail',
            name='Amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plandetail',
            name='ExpiryDate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plandetail',
            name='MediaAdTypeDetail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plandetail',
            name='MediaAdTypeId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plandetail',
            name='MediaDetail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plandetail',
            name='PlanId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plandetail',
            name='StartDate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plandetail',
            name='Status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plandetail',
            name='Vertical',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
