# Generated by Django 3.2.14 on 2023-01-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_media', '0005_auto_20221224_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='BrandCategory',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='BrandName',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='CampaignObjective',
            field=models.TextField(null=True),
        ),
    ]
