# Generated by Django 3.2.14 on 2023-01-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_media', '0006_auto_20230126_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='BrandCategory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='BrandName',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='CampaignObjective',
            field=models.TextField(blank=True, null=True),
        ),
    ]
