# Generated by Django 3.2.14 on 2023-01-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_media', '0007_auto_20230126_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='CartType',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='PaidExcelDownload',
            field=models.IntegerField(default=0),
        ),
    ]
