# Generated by Django 3.2.14 on 2023-03-18 01:48

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesMarketing',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('SalesMarketingId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('ConnectedTo', models.CharField(blank=True, max_length=50, null=True)),
                ('Name', models.CharField(blank=True, max_length=300, null=True)),
                ('Email', models.CharField(blank=True, max_length=300, null=True)),
                ('Phone', models.CharField(blank=True, max_length=300, null=True)),
                ('IsAccountCreated', models.IntegerField(blank=True, null=True)),
                ('ConnectedPersonId', models.CharField(blank=True, max_length=50, null=True)),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('Health', models.CharField(blank=True, max_length=50, null=True)),
                ('JoinedDate', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesMarketingDetail',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('SalesMarketingDetailId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('SalesMarketingId', models.CharField(blank=True, max_length=50, null=True)),
                ('UserId', models.CharField(blank=True, max_length=50, null=True)),
                ('UserType', models.CharField(blank=True, max_length=50, null=True)),
                ('ConnectedThrough', models.CharField(blank=True, max_length=50, null=True)),
                ('ConnectedType', models.CharField(blank=True, max_length=300, null=True)),
                ('MeetingFeedback', models.TextField(blank=True, null=True)),
                ('DetailsShared', models.TextField(blank=True, null=True)),
                ('Comments', models.TextField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('Health', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedDate', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
