# Generated by Django 3.2.14 on 2022-10-08 18:18

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('LoginId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('UserId', models.CharField(max_length=50)),
                ('UserType', models.CharField(max_length=50)),
                ('EmailId', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=300)),
                ('Token', models.CharField(max_length=300)),
                ('Status', models.IntegerField()),
            ],
        ),
    ]
