"""
Django settings for gmk_api project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o=ow9hoh0vt4ijr=nz5c&)5(jlcbzo*v)y)t6s584abej56v3#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['13.212.61.86','3.109.198.207','31103116.globalmediakit.com']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'app_login',
    'app_default',
    'app_admin',
    'app_vertical',
    'app_publisher',
    'app_media',
    'app_advertiser',
    'app_estimate',
    'app_vertical_media',
    'app_gmk_staff',
    'app_site',
    'app_send_mail',
    'app_credit',
    'app_cron_job',
    'app_chat_gpt',
    'app_sales_marketing',
    'app_ad_buzz',
    'app_user_plan',
    'app_estimate_ppt',
    'app_page_seo',
    'app_ai_external'
]

# CORS_ORIGIN_ALLOW_ALL = True
# CORS_ORIGIN_WHITELIST = ('https://globalmediakit.com/','https://www.globalmediakit.com/')
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3030',
]
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gmk_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gmk_api.wsgi.application'
CORS_ORIGIN_ALLOW_ALL = True
# CORS_ORIGIN_WHITELIST = ('https://globalmediakit.com/','https://www.globalmediakit.com/')
# CORS_ALLOWED_ORIGINS = [
#     'https://globalmediakit.com/','https://www.globalmediakit.com/','http://localhost/'
# ]

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }

    #'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'gmk_db',
    #     'USER': 'gmksqluser123',
    #     'PASSWORD': 'uaegmkadminuser123',
    #     'HOST': 'localhost',
    #     'PORT': '3306',
    #     'OPTIONS': {
    #         'sql_mode': 'traditional',
    #     }
    # }
   'default': {
        'ENGINE': 'dj_db_conn_pool.backends.mysql',
        'NAME': 'gmk_db',
        'USER': 'gmksqluser123',
        'PASSWORD': 'uaegmkadminuser123',
        'HOST': 'gmkdatabase.ckd8setjbedc.ap-south-1.rds.amazonaws.com',
        'PORT': '3306',
        'POOL_OPTIONS' : {
            'POOL_SIZE': 40,
            'MAX_OVERFLOW': 40,
            'RECYCLE': 1 * 60 * 60
        },
        'OPTIONS': {
            'sql_mode': 'traditional',
            'charset': 'utf8mb4',
        }
    }
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'gmk_db',
    #     'USER': 'gmk_user_for_db',
    #     'PASSWORD': '!X,r2H0q@k,O',
    #     'HOST': 'localhost',
    #     'PORT': '3306',
    #     'OPTIONS': {
    #         'sql_mode': 'traditional',
    #     }
    
    # }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL='media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_HOST_USER_NAME='Global Media Kit'
EMAIL_HOST_USER = 'adsupport@globalmediakit.com'
EMAIL_HOST_PASSWORD = 'GmkIndia24**'
# EMAIL_HOST_USER = 'media@masscomglobal.com'
# EMAIL_HOST_PASSWORD = 'Gmk2023@**'
# EMAIL_HOST_USER = 'noreply@globalmediakit.com'
# EMAIL_HOST_PASSWORD = 'N0pAgmKFORSiTe2023'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

GMK_MAIL_REGRADS="""Best Regards, 
        <br/>
        Customer Support 
        <br/>
        Global Media Kit"""