# Generated by Django 3.2.14 on 2022-10-10 14:35

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_default', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrderUnit',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('ServiceOrderUnitId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('ServiceOrderUnit', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceUnitType',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('ServiceUnitTypeId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('ServiceUnitType', models.CharField(max_length=300)),
            ],
        ),
    ]
