# Generated by Django 3.2.14 on 2022-12-18 02:30

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_default', '0003_staffpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiserAssistanceSupport',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('AssistanceId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('AssistanceIcon', models.FileField(blank=True, null=True, upload_to='assistanceSupport/vertical_image')),
                ('AssistanceName', models.TextField()),
                ('SupportBy', models.CharField(max_length=300)),
                ('CreditsRequired', models.CharField(max_length=10)),
            ],
        ),
    ]
