# Generated by Django 3.2.14 on 2022-12-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_default', '0004_advertiserassistancesupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiserassistancesupport',
            name='InfoLabel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
