# Generated by Django 3.2.14 on 2022-12-28 19:48

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_default', '0005_advertiserassistancesupport_infolabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationType',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('OrganisationTypeId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('OrganisationType', models.CharField(max_length=300)),
            ],
        ),
    ]
