# Generated by Django 3.2.14 on 2023-02-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_default', '0006_organisationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='vertical',
            name='VerticalIconBW',
            field=models.FileField(blank=True, null=True, upload_to='vertical/vertical_icon'),
        ),
        migrations.AddField(
            model_name='vertical',
            name='VerticalOrder',
            field=models.IntegerField(default=0),
        ),
    ]
