# Generated by Django 3.2.14 on 2023-02-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_default', '0007_auto_20230222_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='adunitcategory',
            name='OrderNo',
            field=models.IntegerField(default=0),
        ),
    ]
