# Generated by Django 3.2.14 on 2022-10-08 18:18

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('AdvertiserId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(blank=True, max_length=300, null=True)),
                ('LastName', models.CharField(blank=True, max_length=300, null=True)),
                ('BusinessEmail', models.CharField(blank=True, max_length=200, null=True)),
                ('CompanyName', models.CharField(blank=True, max_length=300, null=True)),
                ('BuildingNo', models.CharField(blank=True, max_length=300, null=True)),
                ('StreetAddress', models.TextField(blank=True, null=True)),
                ('City', models.CharField(blank=True, max_length=300, null=True)),
                ('State', models.CharField(blank=True, max_length=300, null=True)),
                ('ZIPCode', models.CharField(blank=True, max_length=10, null=True)),
                ('Country', models.CharField(blank=True, max_length=50, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('TargetCountries', models.TextField(blank=True, null=True)),
                ('TargetAudience', models.TextField(blank=True, null=True)),
                ('Status', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
