# Generated by Django 3.2.14 on 2022-11-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertiser', '0002_profile_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Credits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
