# Generated by Django 3.2.14 on 2022-12-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertiser', '0004_profile_phonecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='OrganisationType',
            field=models.TextField(blank=True, null=True),
        ),
    ]
