# Generated by Django 3.2.14 on 2022-12-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertiser', '0006_profile_creditsexpirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='CreditsExpiryDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
