# Generated by Django 3.2.14 on 2022-10-08 18:18

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutOfHome',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('OutOfHomeId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('PublisherId', models.CharField(blank=True, max_length=50, null=True)),
                ('SiteOwnerName', models.CharField(blank=True, max_length=300, null=True)),
                ('CountryEvent', models.CharField(blank=True, max_length=300, null=True)),
                ('CityRegion', models.CharField(blank=True, max_length=300, null=True)),
                ('Location', models.CharField(blank=True, max_length=300, null=True)),
                ('Size', models.CharField(blank=True, max_length=300, null=True)),
                ('Language', models.TextField(blank=True, null=True)),
                ('EstimateReached', models.CharField(blank=True, max_length=300, null=True)),
                ('BenefitsOfAdvertising', models.TextField(blank=True, null=True)),
                ('PromoVideoLink', models.CharField(blank=True, max_length=300, null=True)),
                ('Availability', models.TextField(blank=True, null=True)),
                ('MediaKit', models.FileField(blank=True, null=True, upload_to='vertical/OutOfHome/mediakit')),
                ('MapLink', models.TextField(blank=True, null=True)),
                ('Latitude', models.CharField(blank=True, max_length=300, null=True)),
                ('Longitude', models.CharField(blank=True, max_length=300, null=True)),
                ('IsHyperlocal', models.CharField(blank=True, max_length=300, null=True)),
                ('OutOfHomeImage', models.FileField(blank=True, null=True, upload_to='vertical/OutOfHome/image')),
                ('Status', models.IntegerField(blank=True, null=True)),
                ('ViewsCount', models.IntegerField(blank=True, null=True)),
                ('ModifiedDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutOfHomeImage',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('OutOfHomeImageId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('OutOfHomeId', models.CharField(blank=True, max_length=300, null=True)),
                ('OutOfHomeImage', models.FileField(blank=True, null=True, upload_to='vertical/OutOfHome/image')),
            ],
        ),
        migrations.CreateModel(
            name='OutOfHomeMediaAdType',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('OutOfHomeMediaAdTypeId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('OutOfHomeId', models.CharField(blank=True, max_length=50, null=True)),
                ('MediaAdType', models.CharField(blank=True, max_length=300, null=True)),
                ('SiteName', models.CharField(blank=True, max_length=300, null=True)),
                ('LocationType', models.CharField(blank=True, max_length=300, null=True)),
                ('VerticalTypeId', models.CharField(blank=True, max_length=300, null=True)),
                ('NoOfScreen', models.CharField(blank=True, max_length=300, null=True)),
                ('MediaAdUnitDescription', models.TextField(blank=True, null=True)),
                ('IsDigital', models.CharField(blank=True, max_length=300, null=True)),
                ('SingleRotationTime', models.CharField(blank=True, max_length=10, null=True)),
                ('DurationOfCreative', models.CharField(blank=True, max_length=10, null=True)),
                ('LightingType', models.CharField(blank=True, max_length=300, null=True)),
                ('PackageName', models.CharField(blank=True, max_length=300, null=True)),
                ('PackageType', models.CharField(blank=True, max_length=300, null=True)),
                ('StartDate', models.CharField(blank=True, max_length=300, null=True)),
                ('EndDate', models.CharField(blank=True, max_length=300, null=True)),
                ('NoOfDays', models.CharField(blank=True, max_length=300, null=True)),
                ('MonthlyRentalRate', models.CharField(blank=True, max_length=300, null=True)),
                ('Discount', models.CharField(blank=True, max_length=300, null=True)),
                ('NetCostBeforeTax', models.CharField(blank=True, max_length=300, null=True)),
                ('ProductionCost', models.CharField(blank=True, max_length=300, null=True)),
                ('Tax', models.CharField(blank=True, max_length=300, null=True)),
                ('Availability', models.TextField(blank=True, null=True)),
                ('NetCost', models.CharField(blank=True, max_length=300, null=True)),
                ('RateValidaty', models.CharField(blank=True, max_length=300, null=True)),
                ('AdUnitCategory', models.CharField(blank=True, max_length=50, null=True)),
                ('AdTypeMediaKit', models.FileField(blank=True, null=True, upload_to='vertical/OutOfHome/mediakit')),
                ('AdTypeEstimateReached', models.CharField(blank=True, max_length=300, null=True)),
                ('NearByAdvantages', models.TextField(blank=True, null=True)),
                ('MatchingCategories', models.TextField(blank=True, null=True)),
                ('AgeGroup', models.TextField(blank=True, null=True)),
                ('GenderGroup', models.TextField(blank=True, null=True)),
                ('PromoVideoLink', models.CharField(blank=True, max_length=300, null=True)),
                ('IncomeGroup', models.TextField(blank=True, null=True)),
                ('NationalityCommunity', models.TextField(blank=True, null=True)),
                ('RunAsOffer', models.CharField(blank=True, max_length=300, null=True)),
                ('IsLocalTaxApplied', models.CharField(blank=True, max_length=300, null=True)),
                ('IsNeedApproval', models.CharField(blank=True, max_length=300, null=True)),
                ('NoOfDaysRequired', models.CharField(blank=True, max_length=300, null=True)),
                ('TermsAndConditions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutOfHomeMediaAdTypeImage',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('OutOfHomeMediaAdTypeImageId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('OutOfHomeMediaAdTypeId', models.CharField(blank=True, max_length=300, null=True)),
                ('OutOfHomeMediaAdTypeImage', models.FileField(blank=True, null=True, upload_to='vertical/OutOfHome/image')),
            ],
        ),
    ]
