# Generated by Django 3.2.14 on 2022-10-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vertical_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaadtype',
            name='Currency',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mediaadtype',
            name='Status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
