# Generated by Django 3.2.14 on 2022-12-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vertical_media', '0002_auto_20221013_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaadtype',
            name='RateDisplay',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
