# Generated by Django 3.2.14 on 2023-01-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vertical_media', '0004_alter_mediaadtypeimage_mediaadtypeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='MediaImage',
            field=models.FileField(blank=True, null=True, upload_to='vertical/Media/image'),
        ),
        migrations.AlterField(
            model_name='media',
            name='MediaKit',
            field=models.FileField(blank=True, null=True, upload_to='vertical/Media/mediakit'),
        ),
        migrations.AlterField(
            model_name='mediaadtype',
            name='AdTypeMediaKit',
            field=models.FileField(blank=True, null=True, upload_to='vertical/Media/mediakit'),
        ),
        migrations.AlterField(
            model_name='mediaadtype',
            name='PromoAudio',
            field=models.FileField(blank=True, null=True, upload_to='vertical/Media/audio'),
        ),
        migrations.AlterField(
            model_name='mediaadtype',
            name='ThumbnailImage',
            field=models.FileField(blank=True, null=True, upload_to='vertical/Media/image'),
        ),
        migrations.AlterField(
            model_name='mediaadtypeimage',
            name='MediaAdTypeImage',
            field=models.FileField(blank=True, null=True, upload_to='vertical/Media/image'),
        ),
    ]
