# Generated by Django 3.2.14 on 2023-01-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vertical_media', '0005_auto_20230110_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='WebStatsOnOff',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
