# Generated by Django 3.2.14 on 2023-02-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vertical_media', '0007_media_recommendedmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='MediaCategory',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
