# Generated by Django 3.2.14 on 2023-02-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vertical_media', '0008_media_mediacategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='ViewOnlyMediaStore',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
