# Generated by Django 3.2.14 on 2023-03-18 01:48

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_vertical_media', '0009_media_viewonlymediastore'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaRegionReach',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('MediaRegionReachId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('MediaId', models.CharField(blank=True, max_length=50, null=True)),
                ('CityRegionId', models.CharField(blank=True, max_length=50, null=True)),
                ('EstimateReach', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
