# Generated by Django 3.2.14 on 2023-03-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vertical_media', '0010_mediaregionreach'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='ContactPerson',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaadtype',
            name='SpecificCategory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
